const countries = [
  {code: 'GB', name: 'United Kingdom'},
  {code: 'AL', name: 'Albania'},
  {code: 'AD', name: 'Andorra'},
  {code: 'AT', name: 'Austria'},
  {code: 'AZ', name: 'Azerbaijan'},
  {code: 'BY', name: 'Belarus'},
  {code: 'BE', name: 'Belgium'},
  {code: 'BA', name: 'Bosnia and Herzegovina'},
  {code: 'BG', name: 'Bulgaria'},
  {code: 'HR', name: 'Croatia'},
  {code: 'CY', name: 'Cyprus'},
  {code: 'CZ', name: 'Czech Republic'},
  {code: 'DK', name: 'Denmark'},
  {code: 'EE', name: 'Estonia'},
  {code: 'FI', name: 'Finland'},
  {code: 'FR', name: 'France'},
  {code: 'GE', name: 'Georgia'},
  {code: 'DE', name: 'Germany'},
  {code: 'GI', name: 'Gibraltar'},
  {code: 'GR', name: 'Greece'},
  {code: 'GG', name: 'Guernsey'},
  {code: 'HU', name: 'Hungary'},
  {code: 'IS', name: 'Iceland'},
  {code: 'IE', name: 'Ireland'},
  {code: 'IM', name: 'Isle of Man'},
  {code: 'IT', name: 'Italy'},
  {code: 'JE', name: 'Jersey'},
  {code: 'LV', name: 'Latvia'},
  {code: 'LI', name: 'Liechtenstein'},
  {code: 'LT', name: 'Lithuania'},
  {code: 'LU', name: 'Luxembourg'},
  {code: 'MK', name: 'Macedonia'},
  {code: 'MD', name: 'Moldova'},
  {code: 'MC', name: 'Monaco'},
  {code: 'ME', name: 'Montenegro'},
  {code: 'NL', name: 'Netherlands'},
  {code: 'NO', name: 'Norway'},
  {code: 'PL', name: 'Poland'},
  {code: 'PR', name: 'Portugal'},
  {code: 'RO', name: 'Romania'},
  {code: 'RU', name: 'Russia'},
  {code: 'SM', name: 'San Marino'},
  {code: 'RS', name: 'Serbia'},
  {code: 'SK', name: 'Slovakia'},
  {code: 'SI', name: 'Slovenia'},
  {code: 'ES', name: 'Spain'},
  {code: 'SE', name: 'Sweden'},
  {code: 'CH', name: 'Switzerland'},
  {code: 'TR', name: 'Turkey'},
  {code: 'UA', name: 'Ukraine'},
  {code: 'AR', name: 'Argentina'},
  {code: 'BR', name: 'Brazil'},
  {code: 'CA', name: 'Canada'},
  {code: 'CN', name: 'China'},
  {code: 'HK', name: 'Hong Kong'},
  {code: 'JP', name: 'Japan'},
  {code: 'MX', name: 'Mexico'},
  {code: 'ZA', name: 'South Africa'},
  {code: 'KR', name: 'South Korea'},
  {code: 'US', name: 'United States of America'},
]

module.exports = countries